import type { AIProvider } from '../ai/provider.js';
import type { GitHubClient } from '../github/client.js';
import type { RepoKeeperConfig } from '../config.js';
import { getPRSizeLabel } from './labeler.js';
import { log } from '../logger.js';

interface PRPayload {
  pull_request: {
    number: number;
    title: string;
    body: string | null;
    merged?: boolean;
  };
}

const SUMMARISE_PROMPT = `You are a code review assistant. Summarise the following pull request diff.

PR Title: {title}
PR Description: {description}

Diff:
{diff}

Respond with:
1. A 2-3 sentence plain English summary of what changed and why
2. A list of files changed with a brief (one line) description for each
3. Flags: answer yes/no for each:
   - Breaking changes detected?
   - Tests added or modified?
   - Documentation updated?

Keep your response concise and helpful. Use markdown formatting.`;

const RELEASE_NOTES_PROMPT = `You are a release notes writer. Generate concise release notes for the following merged pull request.

PR Title: {title}
PR Description: {description}

Diff summary (files changed):
{fileSummary}

Write release notes in markdown with:
- A one-line summary of the change
- A bullet list of notable changes (max 5 bullets)
- If there are breaking changes, list them under a "Breaking Changes" heading

Keep it concise and user-facing. Focus on what changed from the user's perspective, not implementation details.`;

export async function handlePullRequest(
  payload: PRPayload,
  ai: AIProvider,
  github: GitHubClient,
  config: RepoKeeperConfig,
): Promise<void> {
  const { number, title, body } = payload.pull_request;

  log('info', `Processing PR #${number}: ${title}`);

  const files = await github.getPRFiles(number);
  const totalLines = files.reduce((sum, f) => sum + f.additions + f.deletions, 0);

  // Apply size label
  const sizeLabel = getPRSizeLabel(totalLines);
  await github.addLabels(number, [sizeLabel]);

  // Only generate AI summary if diff is large enough
  if (totalLines < config.prSummariser.minDiffLines) {
    log('info', `PR #${number} has ${totalLines} lines — below threshold, skipping summary`);
    return;
  }

  const diff = await github.getPRDiff(number);

  // Truncate diff if extremely large (avoid blowing AI context)
  const maxDiffChars = 30_000;
  const truncatedDiff =
    diff.length > maxDiffChars ? diff.slice(0, maxDiffChars) + '\n\n... (diff truncated)' : diff;

  const prompt = SUMMARISE_PROMPT.replace('{title}', title)
    .replace('{description}', body || '(no description)')
    .replace('{diff}', truncatedDiff);

  const summary = await ai.complete(prompt);

  // Build the comment
  const fileList = files
    .map((f) => `- \`${f.filename}\` (+${f.additions}/-${f.deletions}) [${f.status}]`)
    .join('\n');

  const comment =
    `## PR Summary\n\n${summary}\n\n` +
    `### Files Changed (${files.length})\n${fileList}\n\n` +
    `---\n*Size: **${sizeLabel.replace('size/', '')}** (${totalLines} lines changed)*\n` +
    `*Generated by [RepoKeeper](https://github.com/GodsBoy/repokeeper)*`;

  await github.addComment(number, comment);

  log('info', `PR #${number} summarised and labelled as ${sizeLabel}`);
}

export async function handlePullRequestMerged(
  payload: PRPayload,
  ai: AIProvider,
  github: GitHubClient,
  config: RepoKeeperConfig,
): Promise<void> {
  const { number, title, body } = payload.pull_request;

  if (!config.prSummariser.generateReleaseNotes) {
    log('info', `PR #${number} merged but release notes generation is disabled`);
    return;
  }

  log('info', `Generating release notes for merged PR #${number}: ${title}`);

  const files = await github.getPRFiles(number);
  const fileSummary = files
    .map((f) => `- ${f.filename} (+${f.additions}/-${f.deletions}) [${f.status}]`)
    .join('\n');

  const prompt = RELEASE_NOTES_PROMPT.replace('{title}', title)
    .replace('{description}', body || '(no description)')
    .replace('{fileSummary}', fileSummary);

  const releaseNotes = await ai.complete(prompt);

  const comment =
    `## Release Notes\n\n${releaseNotes}\n\n` +
    `---\n*Generated by [RepoKeeper](https://github.com/GodsBoy/repokeeper)*`;

  await github.addComment(number, comment);

  log('info', `Release notes posted for PR #${number}`);
}
